// 365 stoic and philosophical quotes in Danish — one for each day of the year
const QUOTES = [
    // --- Original 30 quotes (1-30) ---
    { text: "Du har magt over dit sind, ikke over ydre begivenheder. Erkend dette og du vil finde styrke.", author: "Marcus Aurelius" },
    { text: "Mist ikke tid på det du ikke kan kontrollere. Fokuser på det du kan.", author: "Epiktet" },
    { text: "Vi lider mere i forestillingen end i virkeligheden.", author: "Seneca" },
    { text: "Lev hver dag som om det kunne være dit sidste — og en dag vil du have ret.", author: "Marcus Aurelius" },
    { text: "Fremgang, ikke perfektion.", author: "Stoisk princip" },
    { text: "Negativt visualisér: hvad ville du miste, hvis du mistede det du har nu?", author: "Irvine" },
    { text: "Det er ikke tingene der forstyrrer os, men vores mening om tingene.", author: "Epiktet" },
    { text: "Hvad er det værste der kan ske? Og kan du overleve det?", author: "Irvine" },
    { text: "Øv frivillig ubehag. Vælg det svære i dag.", author: "Stoisk princip" },
    { text: "Din karakter er summen af dine valg.", author: "Epiktet" },
    { text: "Memento mori: du er dødelig. Hvad betyder det for din dag?", author: "Stoisk princip" },
    { text: "Sammenlign dig ikke med andre. Sammenlign dig kun med dig fra i går.", author: "Stoisk princip" },
    { text: "Hvad er under din kontrol i dag? Fokuser kun på det.", author: "Epiktet" },
    { text: "Enkelthed er styrke. Fjern alt der ikke tjener dit formål.", author: "Stoisk princip" },
    { text: "Forhindringen er vejen. Det der står i vejen, bliver vejen.", author: "Marcus Aurelius" },
    { text: "Vær tolerant over for andre og streng mod dig selv.", author: "Marcus Aurelius" },
    { text: "Lykke er ikke noget der sker for dig. Det er noget du skaber gennem dine handlinger.", author: "Epiktet" },
    { text: "Den bedste hævn er ikke at ligne din fjende.", author: "Marcus Aurelius" },
    { text: "Det er ikke døden en mand skal frygte, men han bør frygte aldrig at begynde at leve.", author: "Marcus Aurelius" },
    { text: "Bær ikke over med hvad skæbnen bringer — brug det.", author: "Seneca" },
    { text: "Vis mig én der ikke er slave. Én er slave af begær, en anden af grådighed, en tredje af ambition.", author: "Seneca" },
    { text: "Svært er det der gør dig stærkere. Undgå ikke modstand — søg den.", author: "Stoisk princip" },
    { text: "Nøglen til lykke er lave forventninger og høj indsats.", author: "Stoisk princip" },
    { text: "Du bliver hvad du gentager. Vælg dine vaner med omhu.", author: "Stoisk princip" },
    { text: "Tiden er din mest begrænsede ressource. Brug den som om den er det.", author: "Seneca" },
    { text: "At leve er ikke bare at trække vejret. Det er at handle.", author: "Seneca" },
    { text: "Ingen kan tage din vilje fra dig. Alt andet er til låns.", author: "Epiktet" },
    { text: "Hold op med at vente. Det rigtige tidspunkt er nu.", author: "Stoisk princip" },
    { text: "Amor fati: elsk din skæbne, også det svære.", author: "Nietzsche / Stoisk princip" },
    { text: "Disciplin er frihed. Uden rutiner styrer tilfældighederne din dag.", author: "Stoisk princip" },

    // --- Marcus Aurelius — Meditations (31-75) ---
    { text: "Når du vågner om morgenen, tænk på hvilket privilegium det er at leve, at tænke, at nyde, at elske.", author: "Marcus Aurelius" },
    { text: "Alt hvad vi hører er en mening, ikke et faktum. Alt hvad vi ser er et perspektiv, ikke sandheden.", author: "Marcus Aurelius" },
    { text: "Sjælen farves af dine tanker. Farv den med de rette.", author: "Marcus Aurelius" },
    { text: "Acceptér de ting som skæbnen binder dig til, og elsk de mennesker skæbnen fører dig til.", author: "Marcus Aurelius" },
    { text: "Det du gør gør en forskel — og du må beslutte, hvilken slags forskel du ønsker at gøre.", author: "Marcus Aurelius" },
    { text: "Tab aldrig synet af, hvor hurtigt tingene passerer forbi og er væk.", author: "Marcus Aurelius" },
    { text: "Grav indad. Indeni er kilden til alt godt, og den kan altid springe frem, hvis du graver.", author: "Marcus Aurelius" },
    { text: "At være vred på nogen er som at drikke gift og forvente, at den anden dør.", author: "Marcus Aurelius" },
    { text: "Du har magt til at trække dig tilbage til dig selv. Ingen tilbagetrækning er mere fredfyldt end den i din egen sjæl.", author: "Marcus Aurelius" },
    { text: "Det er en skam at lade sjælen give op, mens kroppen stadig kæmper.", author: "Marcus Aurelius" },
    { text: "Tænk ikke over, hvad du mangler, men over hvad du har — og husk hvor ivrigt du ville have ønsket det, før du fik det.", author: "Marcus Aurelius" },
    { text: "Hvor meget mere smertefuld er konsekvenserne af vrede end de handlinger, der forårsagede den.", author: "Marcus Aurelius" },
    { text: "Koncentrér ethvert minut som en romer — som en mand — om at gøre det der er foran dig med præcis og ægte alvor.", author: "Marcus Aurelius" },
    { text: "Spild ikke mere tid på at diskutere, hvad en god mand bør være. Vær en.", author: "Marcus Aurelius" },
    { text: "Dit liv er det dine tanker gør det til.", author: "Marcus Aurelius" },
    { text: "Lad hver handling være som den var den sidste i dit liv.", author: "Marcus Aurelius" },
    { text: "Aldrig værdsæt noget, der tvinger dig til at bryde dit løfte, miste din selvrespekt eller hade nogen.", author: "Marcus Aurelius" },
    { text: "I morgen tidlig: sig til dig selv, at du vil møde indiskrete, utaknemlige, voldelige, svigefulde og misundelige mennesker. De er sådan på grund af uvidenhed.", author: "Marcus Aurelius" },
    { text: "Det er ikke hvad der sker for dig, men hvordan du reagerer på det, der betyder noget.", author: "Marcus Aurelius" },
    { text: "Alt er forgængeligt. Både den der husker, og det der huskes.", author: "Marcus Aurelius" },
    { text: "Vær som klippen, som bølgerne bryder sig imod. Den står fast og tæmmer vandets raseri.", author: "Marcus Aurelius" },
    { text: "Naturen har givet os et sind. Brug det som et værktøj, ikke en byrde.", author: "Marcus Aurelius" },
    { text: "Mennesker eksisterer for hinandens skyld. Belær dem eller bær over med dem.", author: "Marcus Aurelius" },
    { text: "At gøre det nødvendige, og præcis som en fornuftig skabning designet af naturen ville gøre det.", author: "Marcus Aurelius" },
    { text: "Ingenting er så vaneformende som at lytte til sig selv tale.", author: "Marcus Aurelius" },
    { text: "Fortvivl aldrig over, at verden er imod dig. Den er for travlt optaget til at tænke på dig.", author: "Marcus Aurelius" },
    { text: "Tag fat i hvert øjeblik som det er: kort, unikt og uigenkaldeligt.", author: "Marcus Aurelius" },
    { text: "Det universelle er forandring. Det personlige er accept.", author: "Marcus Aurelius" },
    { text: "Du kan miste alt — men aldrig dit valg om, hvordan du møder det.", author: "Marcus Aurelius" },
    { text: "Gør det gode. Resten er larm.", author: "Marcus Aurelius" },
    { text: "Opfat hver dag som et helt liv. Fødsel ved daggry, død ved aften.", author: "Marcus Aurelius" },
    { text: "Hvad der ikke gavner sværmen, gavner heller ikke bien.", author: "Marcus Aurelius" },
    { text: "Klag ikke. Bidrag.", author: "Marcus Aurelius" },
    { text: "Det du ikke bruger, forfalder. Brug din tid. Brug din styrke. Brug dit sind.", author: "Marcus Aurelius" },
    { text: "At leve godt er den bedste gengældelse til dem, der tvivlede på dig.", author: "Marcus Aurelius" },
    { text: "Ryd op i dit indre først. Alt ydre følger.", author: "Marcus Aurelius" },
    { text: "Alder er ikke garanteret. Gør dagen vigtig.", author: "Marcus Aurelius" },
    { text: "Du behøver ikke en plan for hele livet. Du behøver en plan for i dag.", author: "Marcus Aurelius" },
    { text: "Alt hvad du møder er træning. Intet er kun ulykke.", author: "Marcus Aurelius" },
    { text: "Den der aldrig har prøvet modstand, kender ikke sin egen styrke.", author: "Marcus Aurelius" },
    { text: "Følelser er gæster. Lad dem komme, mærk dem, og lad dem gå.", author: "Marcus Aurelius" },
    { text: "Det tager mere mod at leve med visdom end at dø med ære.", author: "Marcus Aurelius" },
    { text: "At søge ros er at give andre magt over din glæde.", author: "Marcus Aurelius" },
    { text: "Gør din pligt uden at forvente belønning. Det er nok.", author: "Marcus Aurelius" },
    { text: "Hold op med at ønske tingene var anderledes. Arbejd med det der er.", author: "Marcus Aurelius" },

    // --- Seneca — Letters, Essays (76-130) ---
    { text: "Det er ikke fordi tingene er svære, at vi ikke tør. Det er fordi vi ikke tør, at tingene er svære.", author: "Seneca" },
    { text: "Held er, hvad der sker, når forberedelse møder mulighed.", author: "Seneca" },
    { text: "Vi er oftere bange end sårede, og vi lider mere i vores fantasi end i virkeligheden.", author: "Seneca" },
    { text: "Livet er langt nok — hvis du ved, hvordan du bruger det.", author: "Seneca" },
    { text: "Der er ingen gunstig vind for den, der ikke ved, hvilken havn han sejler mod.", author: "Seneca" },
    { text: "Sandt held er at nyde nuet uden ængstelig afhængighed af fremtiden.", author: "Seneca" },
    { text: "Livet er kort. Spild det ikke på ligegyldigheder.", author: "Seneca" },
    { text: "Svaghed er villig til at finde undskyldninger.", author: "Seneca" },
    { text: "Det er kvaliteten af dine venner, ikke antallet, der betyder noget.", author: "Seneca" },
    { text: "Vrede er et syreholdigt stof der gør mere skade på beholderen end på det, det hældes over.", author: "Seneca" },
    { text: "Vi lærer ikke i skolen, men i livet.", author: "Seneca" },
    { text: "Vanskeligheder styrker sindet, ligesom arbejde styrker kroppen.", author: "Seneca" },
    { text: "Det mest magtfulde er den, der har sig selv i sin magt.", author: "Seneca" },
    { text: "Mens vi venter på at leve, passerer livet os.", author: "Seneca" },
    { text: "Det bedste middel mod vrede er forsinkelse.", author: "Seneca" },
    { text: "Rig er ikke den, der har mest, men den, der behøver mindst.", author: "Seneca" },
    { text: "En mand, der tør spilde én times tid, har ikke opdaget livets værdi.", author: "Seneca" },
    { text: "Begræns ikke dine udfordringer. Udfordr dine begrænsninger.", author: "Seneca" },
    { text: "Vi har to ører og én mund, så vi kan lytte dobbelt så meget, som vi taler.", author: "Seneca" },
    { text: "Lykke er at stoppe ønsket om mere.", author: "Seneca" },
    { text: "Der er ikke noget godt eller dårligt vejr. Kun din reaktion på det.", author: "Seneca" },
    { text: "Lev blandt mennesker, som om Gud ser dig. Tal til Gud, som om mennesker lytter.", author: "Seneca" },
    { text: "At vide er ikke nok. Vi må anvende. At ville er ikke nok. Vi må gøre.", author: "Seneca" },
    { text: "Det vigtigste er ikke hvad du bærer, men hvordan du bærer det.", author: "Seneca" },
    { text: "Forbered dig på det værste, håb på det bedste, og tag imod det der kommer.", author: "Seneca" },
    { text: "Alle skibe er sikre i havn — men det er ikke det, skibe er bygget til.", author: "Seneca" },
    { text: "Et godt sind er en borg, som ingen fjende kan indtage.", author: "Seneca" },
    { text: "At eje for meget er at ejes af dine ting.", author: "Seneca" },
    { text: "Begynd med det samme. Lev, og tæl hver dag som et særskilt liv.", author: "Seneca" },
    { text: "Det er sindet der gør os rige — ikke formuen.", author: "Seneca" },
    { text: "Vis mig en mand, der ikke er slave af noget. Én er slave af lyst, en anden af penge.", author: "Seneca" },
    { text: "Sæt en pris på dig selv, for ellers vil verden gøre det for dig — og den sætter en lav pris.", author: "Seneca" },
    { text: "Ikke hvad du har, men hvad du nyder, udgør din rigdom.", author: "Seneca" },
    { text: "Alle mennesker har fejl. Den stærke indrømmer sine.", author: "Seneca" },
    { text: "Tænk længe over, om du vil lade en ven komme ind. Men når du har besluttet det, så åbn helt.", author: "Seneca" },
    { text: "Den der frygter døden, har allerede stoppet med at leve.", author: "Seneca" },
    { text: "Hvad nytter det at erobre verden, hvis du har mistet dig selv?", author: "Seneca" },
    { text: "Lev i dag. Grib dette øjeblik. Det vender ikke tilbage.", author: "Seneca" },
    { text: "Held er det, vi kalder det, når vi glemmer forberedelsens rolle.", author: "Seneca" },
    { text: "En filosof er ikke den, der tænker mest, men den, der lever bedst.", author: "Seneca" },
    { text: "Problemet er ikke, at vi har for lidt tid. Problemet er, at vi spilder for meget.", author: "Seneca" },
    { text: "At læse uden at reflektere er som at spise uden at fordøje.", author: "Seneca" },
    { text: "Ingen vind er gunstig for den, der ikke har bestemt sin kurs.", author: "Seneca" },
    { text: "Mod er ikke fravær af frygt. Det er at handle på trods af frygten.", author: "Seneca" },
    { text: "Ét af de smukkeste kvaliteter ved sandt venskab: at forstå og blive forstået.", author: "Seneca" },
    { text: "Man må styre skæbnen, eller lade sig styre af den.", author: "Seneca" },
    { text: "Det handler ikke om at have tid. Det handler om at tage tid.", author: "Seneca" },
    { text: "Livet behøver ikke være langt for at være fuldendt.", author: "Seneca" },
    { text: "Vejen til et godt liv er kort: lad være med at bekymre dig om ting udenfor din kontrol.", author: "Seneca" },
    { text: "Jo mere vi ejer, desto mere ejer vores ejendele os.", author: "Seneca" },
    { text: "Kloge mennesker taler, fordi de har noget at sige. Tåber taler, fordi de skal sige noget.", author: "Seneca" },
    { text: "Det stærkeste tegn på visdom er godt humør i vanskelige tider.", author: "Seneca" },
    { text: "Hvert nyt år gør os ikke ældre — det gør os enten klogere eller mere uopmærksomme.", author: "Seneca" },
    { text: "Det er umuligt at leve et behageligt liv uden at leve klogt, retfærdigt og mådeligt.", author: "Seneca" },
    { text: "Den sande styrke viser sig i stilhed, ikke i larm.", author: "Seneca" },

    // --- Epiktet — Discourses, Enchiridion (131-185) ---
    { text: "Frihed er det eneste værdige mål. Og den begynder med at kontrollere dine reaktioner.", author: "Epiktet" },
    { text: "Forlang ikke at begivenheder sker som du ønsker. Ønsk at de sker som de gør, og alt vil gå godt.", author: "Epiktet" },
    { text: "Først og fremmest: sig til dig selv hvad du vil være; og gør derefter hvad du må gøre.", author: "Epiktet" },
    { text: "Den rigtige uddannelse er at lære at ville, hvad der er muligt, i stedet for at kræve det umulige.", author: "Epiktet" },
    { text: "Det er ikke omstændighederne der definerer dig. Det er dine valg.", author: "Epiktet" },
    { text: "Enhver besværlighed i livet giver dig mulighed for at lære noget nyttigt.", author: "Epiktet" },
    { text: "Lidelse opstår ikke af begivenheder, men af vurderingen af begivenheder.", author: "Epiktet" },
    { text: "Den, der ønsker at forbedre sig, må først erkende sin uvidenhed.", author: "Epiktet" },
    { text: "Gør ikke krav på noget der ikke er dit, og du vil aldrig miste noget.", author: "Epiktet" },
    { text: "Prøvelserne viser, hvem du virkelig er.", author: "Epiktet" },
    { text: "To evner har vi fået: at handle og at tåle. Brug begge med visdom.", author: "Epiktet" },
    { text: "Hvis du ønsker fremskridt, vær villig til at virke tåbelig og uvant.", author: "Epiktet" },
    { text: "Vent ikke på at verden ændrer sig. Ændr din egen opfattelse af den.", author: "Epiktet" },
    { text: "En person der konstant klager, har aldrig lært at skelne mellem det, der kan ændres, og det der ikke kan.", author: "Epiktet" },
    { text: "Vejen til magt er at opgive behovet for magt over andre.", author: "Epiktet" },
    { text: "Hold sindet skarpt ved at bruge det dagligt. En ubrugt kniv bliver sløv.", author: "Epiktet" },
    { text: "Overbevis aldrig nogen med ord alene. Vis dem med handling.", author: "Epiktet" },
    { text: "Den frie mand er den, der intet begærer.", author: "Epiktet" },
    { text: "Du kan lænke min krop, men min vilje vil aldrig blive lænket.", author: "Epiktet" },
    { text: "Jo stærkere din tilknytning, desto større din smerte ved tab.", author: "Epiktet" },
    { text: "At undgå prøvelser er at undgå vækst.", author: "Epiktet" },
    { text: "De vigtigste kampe er dem, du kæmper med dig selv.", author: "Epiktet" },
    { text: "Respekt for andre begynder med selvrespekt.", author: "Epiktet" },
    { text: "Vis hvem du er ved hvad du gør, ikke hvad du siger.", author: "Epiktet" },
    { text: "Acceptér hvad der sker. Brug det. Voks med det.", author: "Epiktet" },
    { text: "Vrede løser intet. Den forblinder sindet og fjerner fornuften.", author: "Epiktet" },
    { text: "Det sværeste i livet er at kende dig selv. Det nemmeste er at dømme andre.", author: "Epiktet" },
    { text: "Adlyd naturen, ikke vanen.", author: "Epiktet" },
    { text: "Begær er et fængsel. Nøjsomhed er frihed.", author: "Epiktet" },
    { text: "Selvkontrol er den sande rigdom. Begær er den sande fattigdom.", author: "Epiktet" },
    { text: "Hvad der bekymrer mennesker er ikke tingene i sig selv, men deres forestillinger om dem.", author: "Epiktet" },
    { text: "Vi kan ikke vælge vores ydre omstændigheder, men vi kan altid vælge, hvordan vi reagerer på dem.", author: "Epiktet" },
    { text: "Pas på, at du ikke bliver den person, du kritiserer.", author: "Epiktet" },
    { text: "Start med det lille. Mestre det lille, og det store vil følge.", author: "Epiktet" },
    { text: "At bære byrden med ro er lige så modigt som at kæmpe.", author: "Epiktet" },
    { text: "Dine forventninger bestemmer din tilfredshed. Sænk dem.", author: "Epiktet" },
    { text: "Evnen til at tåle er mere sjælden end evnen til at handle.", author: "Epiktet" },
    { text: "Det hele begynder med et valg. Vælg at være til stede.", author: "Epiktet" },
    { text: "Lev livet i overensstemmelse med din natur — ikke andres forventninger.", author: "Epiktet" },
    { text: "Hvad nytter det at have tusind bøger, hvis du ikke lever efter ét princip?", author: "Epiktet" },
    { text: "At klage er at flygte fra ansvar.", author: "Epiktet" },
    { text: "En vis mand taber aldrig noget — for han sætter ikke sin lykke i ydre ting.", author: "Epiktet" },
    { text: "Den sande sejr er over dig selv.", author: "Epiktet" },
    { text: "Din frihed begynder der, hvor din frygt slutter.", author: "Epiktet" },
    { text: "Tag ansvar. Altid. Ingen undskyldninger.", author: "Epiktet" },
    { text: "Det handler ikke om hvad der sker. Det handler om hvad du gør med det.", author: "Epiktet" },
    { text: "Vis tålmodighed. De fleste problemer løser sig, hvis du giver dem tid.", author: "Epiktet" },
    { text: "Du er ikke din fortid. Du er dit næste valg.", author: "Epiktet" },
    { text: "Tankens kvalitet bestemmer livets kvalitet.", author: "Epiktet" },
    { text: "Livet giver dig, hvad du forbereder dig på at modtage.", author: "Epiktet" },
    { text: "Disciplin i det små bygger styrke til det store.", author: "Epiktet" },
    { text: "Uvidenhed er roden til al lidelse. Søg viden — i dig selv.", author: "Epiktet" },
    { text: "Du træner kroppen dagligt. Gør det samme med sindet.", author: "Epiktet" },
    { text: "Et simpelt liv er et rigt liv.", author: "Epiktet" },
    { text: "Giv slip på det du ikke kan styre, og grib fat i det du kan.", author: "Epiktet" },

    // --- Heraklit (186-205) ---
    { text: "Alt flyder. Intet forbliver det samme.", author: "Heraklit" },
    { text: "Forandring er den eneste konstant.", author: "Heraklit" },
    { text: "Du kan ikke træde i den samme flod to gange.", author: "Heraklit" },
    { text: "Karakter er skæbne.", author: "Heraklit" },
    { text: "Fra strid kommer alt. Modsætninger skaber harmoni.", author: "Heraklit" },
    { text: "Naturen elsker at skjule sig. Den der søger, finder.", author: "Heraklit" },
    { text: "Store resultater kræver stor ambition.", author: "Heraklit" },
    { text: "Ud af enhver modsætning fødes en ny forståelse.", author: "Heraklit" },
    { text: "Den vågne deler én verden. Den sovende lever i sin egen.", author: "Heraklit" },
    { text: "Vejen op og vejen ned er den samme.", author: "Heraklit" },
    { text: "Det modsatte bringer det bedste frem. Sygdom gør sundhed sød. Sult gør mæthed til en gave.", author: "Heraklit" },
    { text: "At lytte ikke til mig, men til fornuften, er visdom.", author: "Heraklit" },
    { text: "Meget lærdom giver ikke forstand.", author: "Heraklit" },
    { text: "Den skjulte harmoni er stærkere end den synlige.", author: "Heraklit" },
    { text: "Tiden er et barn der leger. Et barns rige.", author: "Heraklit" },
    { text: "Det svære er at kende sig selv. Det nemmeste er at vide alt om andre.", author: "Heraklit" },
    { text: "Solen er ny hver dag.", author: "Heraklit" },
    { text: "Hvis du ikke forventer det uventede, vil du ikke finde det.", author: "Heraklit" },
    { text: "Dårlige vidner er øjne og ører for dem, der har barbariske sjæle.", author: "Heraklit" },
    { text: "Den der ikke kender sig selv, kan ikke kende verden.", author: "Heraklit" },

    // --- Musonius Rufus (206-225) ---
    { text: "Vi begynder at miste livet det øjeblik, vi holder op med at stræbe efter at forbedre os.", author: "Musonius Rufus" },
    { text: "Luksus er en ven af grådigheden og en fjende af moderation.", author: "Musonius Rufus" },
    { text: "At spise enkelt er den største luksus.", author: "Musonius Rufus" },
    { text: "En filosof skal ikke leve anderledes end han taler.", author: "Musonius Rufus" },
    { text: "Sult er den bedste krydderi.", author: "Musonius Rufus" },
    { text: "Det er bedre at helbrede sjælen end kroppen — for sjælens sygdomme er farligere.", author: "Musonius Rufus" },
    { text: "Øvelse gør mester — også i dyd.", author: "Musonius Rufus" },
    { text: "Vi bør træne kroppen ikke for at opnå styrke, men for at undgå svaghed.", author: "Musonius Rufus" },
    { text: "At lide uret er bedre end at begå uret.", author: "Musonius Rufus" },
    { text: "Det er bedre at leve med lidt og have fred i sindet end at eje alt og leve i uro.", author: "Musonius Rufus" },
    { text: "Enhver kan filosofere — det kræver blot viljen til at leve bedre.", author: "Musonius Rufus" },
    { text: "Kvinder og mænd har samme evne for dyd. Ingen er fritaget.", author: "Musonius Rufus" },
    { text: "At vise mod er ikke at undgå smerte, men at bære den med værdighed.", author: "Musonius Rufus" },
    { text: "Den bedste måltid er det simpleste. Den bedste dag er den mest produktive.", author: "Musonius Rufus" },
    { text: "Studer ikke kun visdom. Praktisér den dagligt.", author: "Musonius Rufus" },
    { text: "En stærk krop uden en stærk sjæl er som et smukt hus uden fundament.", author: "Musonius Rufus" },
    { text: "Filosofi er ikke teori. Det er en daglig praksis for at leve bedre.", author: "Musonius Rufus" },
    { text: "Overflod gør mennesket svagt. Nøjsomhed gør det stærkt.", author: "Musonius Rufus" },
    { text: "De bedste lektioner kommer fra handling, ikke fra ord.", author: "Musonius Rufus" },
    { text: "At kontrollere sin appetit er det første skridt mod selvbeherskelse.", author: "Musonius Rufus" },

    // --- Cato (226-240) ---
    { text: "Jeg vil hellere gøre det rigtige og mislykkes end gøre det forkerte og lykkes.", author: "Cato" },
    { text: "Handling, ikke tale, er den sande test af karakter.", author: "Cato" },
    { text: "Bitter er den sande medicin. Behagelige løgne helbreder intet.", author: "Cato" },
    { text: "En mand af visdom frygter ikke døden. Han frygter et meningsløst liv.", author: "Cato" },
    { text: "Vær forberedt. Skæbnen favoriserer den, der er klar.", author: "Cato" },
    { text: "Grib dagen med begge hænder. Slip hvad der ikke tjener dig.", author: "Cato" },
    { text: "Ære er ikke hvad andre siger om dig. Det er hvad du gør, når ingen ser.", author: "Cato" },
    { text: "Den stærkeste mand er den, der kan styre sig selv.", author: "Cato" },
    { text: "At tale er sølv. At tie er guld. At handle er diamant.", author: "Cato" },
    { text: "Vælg det svære, for det lette gør dig svag.", author: "Cato" },
    { text: "At kæmpe for en sag er bedre end at leve uden en.", author: "Cato" },
    { text: "Hellere dø på fødderne end leve på knæene.", author: "Cato" },
    { text: "Et liv uden mod er et liv halvt levet.", author: "Cato" },
    { text: "Det nytter ikke at klage over vejret. Gå ud alligevel.", author: "Cato" },
    { text: "Vis din karakter når det er svært. Det er let at være god, når alt går godt.", author: "Cato" },

    // --- Zenon af Citium (241-255) ---
    { text: "Vi har to ører og én mund — for at lytte mere end vi taler.", author: "Zenon af Citium" },
    { text: "Velvære er det gode flow af livet.", author: "Zenon af Citium" },
    { text: "Menneskets mål er at leve i overensstemmelse med naturen.", author: "Zenon af Citium" },
    { text: "Ingen tab er større end at spilde tid.", author: "Zenon af Citium" },
    { text: "Dyd er den eneste sande rigdom.", author: "Zenon af Citium" },
    { text: "Fornuften er den bedste vejleder i livet.", author: "Zenon af Citium" },
    { text: "Lev i harmoni med verden, eller lev i konflikt med dig selv.", author: "Zenon af Citium" },
    { text: "Den kloge mand siger kun det nødvendige.", author: "Zenon af Citium" },
    { text: "En ydre tilfredsstillelse er altid flygtig. Indre ro varer.", author: "Zenon af Citium" },
    { text: "Et godt liv er resultatet af rette handlinger, ikke rette omstændigheder.", author: "Zenon af Citium" },
    { text: "At leve i overensstemmelse med naturen er at leve i overensstemmelse med dyd.", author: "Zenon af Citium" },
    { text: "Den vise handler, den dumme reagerer.", author: "Zenon af Citium" },
    { text: "Selvbeherskelse er fundamentet for alle andre dyder.", author: "Zenon af Citium" },
    { text: "Intet ydre kan true den, der har indre styrke.", author: "Zenon af Citium" },
    { text: "Det sande mål er ikke lykke, men at fortjene den.", author: "Zenon af Citium" },

    // --- Chrysippos (256-265) ---
    { text: "Universet er et levende, fornuftigt væsen. Vi er dele af det.", author: "Chrysippos" },
    { text: "Det er den vise mands opgave at undgå problemer, ikke at overvinde dem.", author: "Chrysippos" },
    { text: "At leve vel er at leve i overensstemmelse med erfaringen af de ting, der sker af naturen.", author: "Chrysippos" },
    { text: "Lidenskaberne er fejlbedømmelser af sindet. Korriger tanken, og følelsen følger.", author: "Chrysippos" },
    { text: "Et skib der aldrig sejler, rådner i havnen.", author: "Chrysippos" },
    { text: "At forstå verden begynder med at forstå sig selv.", author: "Chrysippos" },
    { text: "Passioner er sygdomme i sjælen. Dyd er helbredelsen.", author: "Chrysippos" },
    { text: "Det fornuftige valg er altid tilgængeligt, selv under pres.", author: "Chrysippos" },
    { text: "Livet er en kæde af årsager. Acceptér kæden, og du finder fred.", author: "Chrysippos" },
    { text: "Uorden i sindet skaber uorden i livet.", author: "Chrysippos" },

    // --- Kleanthes (266-275) ---
    { text: "Led mig, O Skæbne, hvorhen du vil. Jeg følger villigt. Gør jeg det ikke, må jeg alligevel.", author: "Kleanthes" },
    { text: "Livets formål er at tjene og vise medfølelse og vilje til at hjælpe andre.", author: "Kleanthes" },
    { text: "Den der kæmper mod skæbnen, slæbes af den. Den der accepterer den, ledes.", author: "Kleanthes" },
    { text: "Alt sker for en grund. Din opgave er at finde den.", author: "Kleanthes" },
    { text: "Styrk din sjæl, som du styrker din krop. Daglig øvelse.", author: "Kleanthes" },
    { text: "At udholde er en dyd. At klage er en svaghed.", author: "Kleanthes" },
    { text: "Modgang er guddommelig træning. Tag imod den med taknemmelighed.", author: "Kleanthes" },
    { text: "Visdom er ikke at vide alt. Det er at handle korrekt med det, du ved.", author: "Kleanthes" },
    { text: "Den sande styrke ligger i at acceptere livets vilkår med ro i sindet.", author: "Kleanthes" },
    { text: "Følg fornuften, og du vil aldrig fare vild.", author: "Kleanthes" },

    // --- Nietzsche (276-295) ---
    { text: "Den der har et hvorfor at leve for, kan bære næsten ethvert hvordan.", author: "Nietzsche" },
    { text: "Du må have kaos i dig for at føde en dansende stjerne.", author: "Nietzsche" },
    { text: "Det der ikke slår mig ihjel, gør mig stærkere.", author: "Nietzsche" },
    { text: "At leve er at lide. At overleve er at finde mening i lidelsen.", author: "Nietzsche" },
    { text: "Bliv den du er.", author: "Nietzsche" },
    { text: "Sandheden er hård. Men den er vejen til vækst.", author: "Nietzsche" },
    { text: "Uden musik ville livet være en fejltagelse.", author: "Nietzsche" },
    { text: "Håb er livets skuespil. Det holder os i gang, selv i det mørkeste.", author: "Nietzsche" },
    { text: "Stor fare kræver stort mod. Intet stort blev opnået uden risiko.", author: "Nietzsche" },
    { text: "Den, der kæmper mod monstre, bør passe på ikke selv at blive et monster.", author: "Nietzsche" },
    { text: "Ensomhed er den vises skole.", author: "Nietzsche" },
    { text: "Mennesker stræber ikke efter lykke. Det gør kun englænderen.", author: "Nietzsche" },
    { text: "Ingen kunstner tolererer virkeligheden. Derfor skaber han sin egen.", author: "Nietzsche" },
    { text: "Foragt for dig selv er det første skridt mod selvforbedring.", author: "Nietzsche" },
    { text: "Det kræver mere mod at ændre sin mening end at holde fast i den.", author: "Nietzsche" },
    { text: "I hvert kaos er der en orden. I hver uorden en skjult kosmos.", author: "Nietzsche" },
    { text: "Den, der ved hvorfor han lever, kan udholde næsten enhver tilstand.", author: "Nietzsche" },
    { text: "At elske sin skæbne er den højeste form for accept.", author: "Nietzsche" },
    { text: "Dybden af din lidelse bestemmer højden af din karakter.", author: "Nietzsche" },
    { text: "Overvind dig selv, og du har overvundet din farligste fjende.", author: "Nietzsche" },

    // --- William B. Irvine (296-315) ---
    { text: "Den nemmeste vej til lykke er at ville det du allerede har.", author: "Irvine" },
    { text: "Negativ visualisering er nøglen til taknemmelighed. Forestil dig tabet, og du vil elske hvad du har.", author: "Irvine" },
    { text: "Øv dig i at skelne mellem det du kan kontrollere og det du ikke kan.", author: "Irvine" },
    { text: "Sæt personlige mål ud fra indsats, ikke resultater.", author: "Irvine" },
    { text: "At søge komfort er at undgå vækst.", author: "Irvine" },
    { text: "Stoicisme er ikke følelsesløshed. Det er følelsesmæssig intelligens.", author: "Irvine" },
    { text: "Din værste fjende er din tendens til at ville have mere.", author: "Irvine" },
    { text: "Forestil dig at du aldrig havde prøvet det, du tager for givet. Se det med nye øjne.", author: "Irvine" },
    { text: "Tilfredshed er ikke at have alt. Det er at nyde det du har.", author: "Irvine" },
    { text: "De stoiske teknikker er enkle. Det svære er at huske at bruge dem.", author: "Irvine" },
    { text: "Frivillig ubehag er vaccinen mod livets uundgåelige lidelse.", author: "Irvine" },
    { text: "En stoiker stræber ikke efter rigdom, men efter immunitet overfor fattigdom.", author: "Irvine" },
    { text: "Ros og kritik bør have samme effekt på dig: ingen.", author: "Irvine" },
    { text: "At have lave forventninger er ikke pessimisme. Det er strategi.", author: "Irvine" },
    { text: "En god dag er ikke en dag uden problemer. Det er en dag, hvor du håndterede dem godt.", author: "Irvine" },
    { text: "Den der er taknemlig for det lille, har altid nok.", author: "Irvine" },
    { text: "Forvent modgang. Bliv overrasket over glæde.", author: "Irvine" },
    { text: "Mål din dag på indsats, ikke på held.", author: "Irvine" },
    { text: "Det gode liv kræver øvelse, ikke held.", author: "Irvine" },
    { text: "Lykke er et biprodukt af at leve dydig — ikke et mål i sig selv.", author: "Irvine" },

    // --- Stoiske principper (316-365) ---
    { text: "Morgenrutinen er fundamentet. Start dagen med intention.", author: "Stoisk princip" },
    { text: "Aftenrefleksion: hvad gik godt, hvad kan forbedres, hvad er du taknemlig for?", author: "Stoisk princip" },
    { text: "Øv dig i at sige nej. Ikke alt fortjener din energi.", author: "Stoisk princip" },
    { text: "Søvn er hellig. En udmattet krop producerer et svagt sind.", author: "Stoisk princip" },
    { text: "Bevæg dig hver dag. Kroppen er sind, og sindet er krop.", author: "Stoisk princip" },
    { text: "Skærmtid er den moderne stoikers fjende. Styr den, eller den styrer dig.", author: "Stoisk princip" },
    { text: "En journal er et spejl for sjælen. Skriv dagligt.", author: "Stoisk princip" },
    { text: "Små vaner, store resultater. Konsistens slår intensitet.", author: "Stoisk princip" },
    { text: "Den der kender sine svagheder, har en styrke.", author: "Stoisk princip" },
    { text: "At bede om hjælp er styrke, ikke svaghed.", author: "Stoisk princip" },
    { text: "Tavsheden har mere at lære dig end larmen.", author: "Stoisk princip" },
    { text: "En enkel kost giver et klart sind.", author: "Stoisk princip" },
    { text: "Naturen er din bedste lærer. Gå udenfor.", author: "Stoisk princip" },
    { text: "Bliv ven med ubehag. Det er din bedste træner.", author: "Stoisk princip" },
    { text: "En dag uden refleksion er en dag spildt.", author: "Stoisk princip" },
    { text: "Giv mere end du tager. Altid.", author: "Stoisk princip" },
    { text: "Perfektionisme er prokrastinering i forklædning.", author: "Stoisk princip" },
    { text: "At forgive er at befri dig selv.", author: "Stoisk princip" },
    { text: "Handling kurerer frygt. Stilstand fodrer den.", author: "Stoisk princip" },
    { text: "Hvad du tolererer, bliver dit liv. Hæv standarden.", author: "Stoisk princip" },
    { text: "Rutiner er ikke kedelige. De er fundamentet for frihed.", author: "Stoisk princip" },
    { text: "Dine ord former din verden. Vælg dem med omhu.", author: "Stoisk princip" },
    { text: "Et stille sind er et skarpt sind.", author: "Stoisk princip" },
    { text: "Giv dig selv lov til at fejle. Det er sådan du lærer.", author: "Stoisk princip" },
    { text: "Selvmedlidenhed er gift. Selvdisciplin er medicin.", author: "Stoisk princip" },
    { text: "Vis taknemmelighed aktivt, ikke kun i tanken.", author: "Stoisk princip" },
    { text: "Fokus er en superkraft. Distraktioner er din kryptonit.", author: "Stoisk princip" },
    { text: "At eje mindre giver plads til at leve mere.", author: "Stoisk princip" },
    { text: "Et klart mål gør svære valg lette.", author: "Stoisk princip" },
    { text: "Tag den koldeste bruser. Mærk livskraften.", author: "Stoisk princip" },
    { text: "Du skylder dig selv sandheden. Altid.", author: "Stoisk princip" },
    { text: "Et kort liv med mening slår et langt liv uden.", author: "Stoisk princip" },
    { text: "Den der intet forventer, kan aldrig blive skuffet.", author: "Stoisk princip" },
    { text: "Stil dig op, når du har lyst til at blive liggende.", author: "Stoisk princip" },
    { text: "Ydmyghed er ikke svaghed. Det er styrke med selvindsigt.", author: "Stoisk princip" },
    { text: "At lytte er en sjælden og undervurderet kunst.", author: "Stoisk princip" },
    { text: "Dyd er svært. Det er derfor det er værdifuldt.", author: "Stoisk princip" },
    { text: "Lev så du ikke fortryder. Gør det rigtige, også når det koster.", author: "Stoisk princip" },
    { text: "Morgendagen eksisterer ikke endnu. I dag er det eneste du har.", author: "Stoisk princip" },
    { text: "Alt begynder med det første skridt. Tag det nu.", author: "Stoisk princip" },
    { text: "Sæt pris på det der virkelig tæller: sundhed, relationer, indre fred.", author: "Stoisk princip" },
    { text: "At mestre sig selv er den største bedrift.", author: "Stoisk princip" },
    { text: "Lad ikke andres kaos blive dit.", author: "Stoisk princip" },
    { text: "Gør det nødvendige. Derefter det mulige. Pludselig gør du det umulige.", author: "Stoisk princip" },
    { text: "Hvert eneste valg er en stemme på den person, du vil være.", author: "Stoisk princip" },
    { text: "Ro er en daglig øvelse, ikke en tilstand du opnår én gang.", author: "Stoisk princip" },
    { text: "Det du modstår, varer ved. Det du accepterer, transformerer dig.", author: "Stoisk princip" },
    { text: "Et liv uden udfordring er et liv uden vækst.", author: "Stoisk princip" },
    { text: "Den bedste investering er i dig selv. Alt andet er sekundært.", author: "Stoisk princip" },
    { text: "I dag er en gave. Brug den klogt.", author: "Stoisk princip" },

    // --- Søren Kierkegaard ---
    { text: "Livet kan kun forstås bagud; men det skal leves fremad.", author: "Søren Kierkegaard" },
    { text: "At vove er at miste fodfæste for en stund. Ikke at vove er at miste sig selv.", author: "Søren Kierkegaard" },
    { text: "Den største fare for et menneske er at miste sig selv og leve som alle andre.", author: "Søren Kierkegaard" },
    { text: "Angst er frihedens svimmelhed.", author: "Søren Kierkegaard" },
    { text: "Den der vælger at vove, risikerer at fejle. Den der ikke vælger, fejler altid.", author: "Søren Kierkegaard" },
    { text: "Det at elske et andet menneske er at ville det bedste for dette menneske.", author: "Søren Kierkegaard" },
    { text: "Det vigtigste er ikke hvem du er i andres øjne, men hvem du er i dine egne.", author: "Søren Kierkegaard" },
    { text: "Fortvivlelse er at miste sig selv. Håb er at finde sig selv igen.", author: "Søren Kierkegaard" },
    { text: "Den sande frihed opstår, når du vælger dig selv fuldt ud.", author: "Søren Kierkegaard" },
    { text: "Kun den der kender sit eget mørke, kan virkelig sætte pris på lyset.", author: "Søren Kierkegaard" },
    { text: "At vælge er at ofre alt det man ikke vælger — og alligevel vælge.", author: "Søren Kierkegaard" },
    { text: "Kærlighed er ikke en følelse alene, men en beslutning man tager igen og igen.", author: "Søren Kierkegaard" },
    { text: "Den der ikke er villig til at fejle, er heller ikke villig til at vokse.", author: "Søren Kierkegaard" },
    { text: "Autenticitet kræver mod. Det er lettere at efterligne end at være sig selv.", author: "Søren Kierkegaard" },
    { text: "Den reneste form for galskab er at lade alt forblive, som det er, og håbe på forandring.", author: "Søren Kierkegaard" },
    { text: "Selvforståelse er en livslang opgave, ikke en destination.", author: "Søren Kierkegaard" },
    { text: "Det indre liv er det eneste, der virkelig er dit.", author: "Søren Kierkegaard" },
    { text: "Tålmodighed er nødvendig for at bære sine egne fejl med nåde.", author: "Søren Kierkegaard" },
    { text: "Springet er selve essensen af tro — og af livet.", author: "Søren Kierkegaard" },
    { text: "Den der forstår, at alt er muligt, vil kræve det mulige af sig selv.", author: "Søren Kierkegaard" },

    // --- Viktor Frankl ---
    { text: "Mellem stimulus og respons er der et rum. I det rum er vores frihed til at vælge.", author: "Viktor Frankl" },
    { text: "Den der har et 'hvorfor' at leve for, kan bære næsten ethvert 'hvordan'.", author: "Viktor Frankl" },
    { text: "Lykke kan ikke jages. Den følger med som en sideeffekt af det meningsfulde liv.", author: "Viktor Frankl" },
    { text: "Når vi ikke længere kan ændre en situation, er vi udfordret til at ændre os selv.", author: "Viktor Frankl" },
    { text: "Alt kan tages fra et menneske på nær én ting: friheden til at vælge sin indstilling.", author: "Viktor Frankl" },
    { text: "Mening er ikke noget man finder. Det er noget man skaber gennem sine valg.", author: "Viktor Frankl" },
    { text: "Lidelse ophører med at være lidelse i det øjeblik, den finder sin mening.", author: "Viktor Frankl" },
    { text: "Et menneske kan bære hvad som helst, hvis det ved hvorfor.", author: "Viktor Frankl" },

    // --- Albert Camus ---
    { text: "Man skal forestille sig Sisyfos lykkelig.", author: "Albert Camus" },
    { text: "I midten af vinter fandt jeg endelig, at der inde i mig lå en uovervindelig sommer.", author: "Albert Camus" },
    { text: "Oprøret er det eneste reelle modsvar til det absurde liv.", author: "Albert Camus" },
    { text: "At leve fuldt ud er at acceptere, at intet varer — og handle alligevel.", author: "Albert Camus" },
    { text: "Den der fortvivler over begivenheder, er en kujon. Den der glæder sig over dem, er en idiot.", author: "Albert Camus" },

    // --- Friedrich Nietzsche ---
    { text: "Du skal blive den du er.", author: "Friedrich Nietzsche" },
    { text: "At vokse er at overskride sig selv — igen og igen.", author: "Friedrich Nietzsche" },
    { text: "Den der har et 'hvorfor', kan klare næsten ethvert 'hvordan'.", author: "Friedrich Nietzsche" },
    { text: "Den der kæmper mod monstre, bør passe på ikke selv at blive et.", author: "Friedrich Nietzsche" },

    // --- Ralph Waldo Emerson ---
    { text: "Det eneste, der kan give dig varig fred, er dig selv.", author: "Ralph Waldo Emerson" },
    { text: "Gør det du frygter, og din frygt dør med sikkerhed.", author: "Ralph Waldo Emerson" },
    { text: "Tillid til dig selv er hemmeligheden bag enhver succes.", author: "Ralph Waldo Emerson" },
    { text: "Vær dig selv. Enhver anden rolle er allerede besat.", author: "Ralph Waldo Emerson" },
    { text: "En tanke er et handlingsfrø — plant det rigtigt.", author: "Ralph Waldo Emerson" },
    { text: "Det at rejse er ikke at flygte. Det er at opdage, hvad der altid var der.", author: "Ralph Waldo Emerson" },

    // --- Henry David Thoreau ---
    { text: "Gå trygt i den retning dine drømme leder dig. Lev det liv, du forestiller dig.", author: "Henry David Thoreau" },
    { text: "Prisen er det du betaler. Værdien er det du får.", author: "Henry David Thoreau" },
    { text: "Det er ikke nok at være flittig. Hvad er du flittig om?", author: "Henry David Thoreau" },
    { text: "Lev bevidst. Gør ingenting af vane, men af vilje.", author: "Henry David Thoreau" },
    { text: "Rigdom er evnen til at opleve livet fuldt ud.", author: "Henry David Thoreau" },

    // --- Rumi ---
    { text: "Lev, hvor du frygter at leve.", author: "Rumi" },
    { text: "Ud over ideer om ret og uret er der en mark. Jeg mødes med dig der.", author: "Rumi" },
    { text: "Hvad du søger, søger dig.", author: "Rumi" },
    { text: "Sår er de steder, lyset kommer ind.", author: "Rumi" },
    { text: "Lad stilheden fortælle dig sandheden.", author: "Rumi" },
    { text: "Det du søger udenfor dig selv, er allerede inden i dig.", author: "Rumi" },

    // --- Michel de Montaigne ---
    { text: "Jeg studerer mig selv mere end noget andet emne. Det er min metafysik.", author: "Michel de Montaigne" },
    { text: "At filosofere er at lære at dø.", author: "Michel de Montaigne" },
    { text: "Hvert menneske bærer hele menneskenes betingelse i sig.", author: "Michel de Montaigne" },
    { text: "Intet er så svært som at kende sig selv — og intet er mere nødvendigt.", author: "Michel de Montaigne" },
    { text: "Den største ting i verden er at vide, hvordan man tilhører sig selv.", author: "Michel de Montaigne" },

    // --- Aristoteles ---
    { text: "Vi er det vi gentagne gange gør. Fremragenhed er ikke en handling, men en vane.", author: "Aristoteles" },
    { text: "Lykken er den endelige hensigt med det menneskelige liv.", author: "Aristoteles" },
    { text: "Den der intet spørger, lærer intet.", author: "Aristoteles" },
    { text: "Klogskab er evnen til at skelne det gode fra det gode på det rette tidspunkt.", author: "Aristoteles" },
    { text: "Det er karakteren, der afslører mennesket — ikke ord, men handlinger.", author: "Aristoteles" },

    // --- William James ---
    { text: "Den største revolution i min generation er opdagelsen af, at man kan ændre sit liv ved at ændre sine tanker.", author: "William James" },
    { text: "Handl som om du allerede er den person, du ønsker at blive.", author: "William James" },
    { text: "At vide er ikke nok. Man må anvende det man ved.", author: "William James" },
    { text: "Visdom er evnen til at håndtere det uafgørlige.", author: "William James" },

    // --- Arthur Schopenhauer ---
    { text: "Talent rammer et mål, ingen kan ramme. Geni rammer et mål, ingen kan se.", author: "Arthur Schopenhauer" },
    { text: "Det meste menneskelig lidelse opstår ikke af dårligdom, men af uvidenhed.", author: "Arthur Schopenhauer" },
    { text: "Sundhed er ikke alt, men uden sundhed er alt ingenting.", author: "Arthur Schopenhauer" },
    { text: "At læse er at låne andres tanker. At tænke er at mønte sine egne.", author: "Arthur Schopenhauer" },

    // --- Lao Tzu ---
    { text: "En rejse på tusind mil begynder med et enkelt skridt.", author: "Lao Tzu" },
    { text: "Kend andre, og du er klog. Kend dig selv, og du er oplyst.", author: "Lao Tzu" },
    { text: "Stil dig i problemer, mens de er små.", author: "Lao Tzu" },
    { text: "Vand er blødt, men det river sten itu med tålmodighed.", author: "Lao Tzu" },
    { text: "At have uden at eje. At handle uden at forvente. At lede uden at kontrollere.", author: "Lao Tzu" },
];
